image: gitpod/workspace-dotnet

vscode:
  extensions:
    - muhammad-sammy.csharp
    - ionide.ionide-fsharp

tasks:
  - init: >
      dotnet tool restore
      dotnet paket restore
      dotnet run --project build/Build.fsproj
