name: Build

on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        dotnet: [6.0.200]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore tools
      run: dotnet tool restore
    - name: Build
      run: dotnet run --project build/Build.fsproj
